language: node_js
node_js:
  - "node"
  - "iojs"
  - "6.0"
  - "5.0"
  - "4.2"
  - "0.12"
  - "0.10"
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'